version: '3.8'
services:
  rabbitmq-1:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-1
    hostname: rabbitmq-1
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=DSHEVCXBBETJJVJWTOWT
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    networks:
      - applications-network
networks:
  applications-network:
      name: applications-network
volumes:
  rabbitmq:
