name: Update rabbitmq
on: push
jobs:
  
  create-folder:
    name: Create folder
    runs-on: ubuntu-latest
    steps:
    - name: Create folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RECETTE_APPLICATIONS_HOST }}
        port: ${{ secrets.RECETTE_APPLICATIONS_PORT }}
        username: ${{ secrets.RECETTE_APPLICATIONS_USERNAME }}
        key: ${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}
        script: |
          sudo mkdir -p /opt/shared-tools/rabbitmq
          sudo chmod ugo+rwx /opt/shared-tools/rabbitmq

  copy-configs:
    name: "copy docker-compose configs"
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RECETTE_APPLICATIONS_HOST }}
          port: ${{ secrets.RECETTE_APPLICATIONS_PORT }}
          username: ${{ secrets.RECETTE_APPLICATIONS_USERNAME }}
          key: ${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}
          source: "rabbitmq"
          target: "/opt/shared-tools"

  run-container:
    name: "Run container"
    runs-on: ubuntu-latest
    needs: [copy-configs]
    steps:
    - name: Run container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RECETTE_APPLICATIONS_HOST }}
        port: ${{ secrets.RECETTE_APPLICATIONS_PORT }}
        username: ${{ secrets.RECETTE_APPLICATIONS_USERNAME }}
        key: ${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}
        script: |
          docker compose -f /opt/shared-tools/rabbitmq/docker-compose.yml stop
          docker compose -f /opt/shared-tools/rabbitmq/docker-compose.yml rm -f
          docker compose -f /opt/shared-tools/rabbitmq/docker-compose.yml up -d